const CODE_MAP: Record<string, string> = {
  KeyA: 'A', KeyB: 'B', KeyC: 'C', KeyD: 'D', KeyE: 'E',
  KeyF: 'F', KeyG: 'G', KeyH: 'H', KeyI: 'I', KeyJ: 'J',
  KeyK: 'K', KeyL: 'L', KeyM: 'M', KeyN: 'N', KeyO: 'O',
  KeyP: 'P', KeyQ: 'Q', KeyR: 'R', KeyS: 'S', KeyT: 'T',
  KeyU: 'U', KeyV: 'V', KeyW: 'W', KeyX: 'X', KeyY: 'Y',
  KeyZ: 'Z',
  Digit0: '0', Digit1: '1', Digit2: '2', Digit3: '3', Digit4: '4',
  Digit5: '5', Digit6: '6', Digit7: '7', Digit8: '8', Digit9: '9',
  F1: 'F1',   F2: 'F2',   F3: 'F3',   F4: 'F4',   F5: 'F5',  F6: 'F6',
  F7: 'F7',   F8: 'F8',   F9: 'F9',   F10: 'F10', F11: 'F11', F12: 'F12',
  Space:          'SPACE',
  Enter:          'RETURN',
  NumpadEnter:    'NUMPADENTER',
  Backspace:      'BACK',
  Tab:            'TAB',
  CapsLock:       'CAPITAL',
  ShiftLeft:      'LSHIFT',    ShiftRight:   'RSHIFT',
  ControlLeft:    'LCONTROL',  ControlRight: 'RCONTROL',
  AltLeft:        'LALT',      AltRight:     'RALT',
  ArrowUp:        'UP',        ArrowDown:    'DOWN',
  ArrowLeft:      'LEFT',      ArrowRight:   'RIGHT',
  Delete:         'DELETE',    Insert:       'INSERT',
  Home:           'HOME',      End:          'END',
  PageUp:         'PRIOR',     PageDown:     'NEXT',
  Numpad0: 'NUMPAD0', Numpad1: 'NUMPAD1', Numpad2: 'NUMPAD2',
  Numpad3: 'NUMPAD3', Numpad4: 'NUMPAD4', Numpad5: 'NUMPAD5',
  Numpad6: 'NUMPAD6', Numpad7: 'NUMPAD7', Numpad8: 'NUMPAD8',
  Numpad9: 'NUMPAD9',
  NumpadAdd:      'ADD',      NumpadSubtract: 'SUBTRACT',
  NumpadMultiply: 'MULTIPLY', NumpadDivide:   'DIVIDE',
  NumpadDecimal:  'DECIMAL',
  Minus:       'OEM_MINUS', Equal:        'OEM_PLUS',
  BracketLeft: 'OEM_4',     BracketRight: 'OEM_6',
  Semicolon:   'OEM_1',     Quote:        'OEM_7',
  Comma:       'OEM_COMMA', Period:       'OEM_PERIOD',
  Slash:       'OEM_2',     Backslash:    'OEM_5',
  Backquote:   'OEM_3',
}

export function codeToFivemKey(code: string): string | null {
  return CODE_MAP[code] ?? null
}
